sudo: required
services:
  - docker
before_install:
  - docker build -t yh515511038/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true yh515511038/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-975534643538"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
